#!/usr/bin/env python3

from gradelib import *

r = Runner(save("xv6.out"))

@test(1, "usertests (slow)")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -s'
    ]), timeout=900)
    r.match('^ALL TESTS PASSED$')

run_tests()
